### ISSUE TITLE
Any way to disable appending [m] to messages?

### ISSUE THREAD

**Issue by tfreedman** [kfatehi/matrix-puppet-facebook#6]
I've been using this bridge in production for the past couple weeks, and most things are totally fine (except for the bugs I've filed). However, a common complaint with the people I talk to is that [m] gets appended when I'm not using Facebook Messenger natively.

Is there a nice way to disable this, so that nobody needs to know how I'm replying?

**Comment by kfatehi** [comment]
Yup we have had success using non printable characters on other services.
I'll update this issue later when I'm at a computer with the exact details.

On Thu, Jan 26, 2017 at 4:45 PM Tyler Freedman <notifications@github.com>
wrote:

I've been using this bridge in production for the past couple weeks, and
most things are totally fine (except for the bugs I've filed). However, a
common complaint with the people I talk to is that [m] gets appended when
I'm not using Facebook Messenger natively.

Is there a nice way to disable this, so that nobody needs to know how I'm
replying?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kfatehi/matrix-puppet-facebook/issues/6>, or mute the
thread

**Comment by kfatehi** [comment]
@tfreedman [here](https://github.com/AndrewJDR/matrix-puppet-bridge/blob/f2aee74e0cf102775ae06529759c3aa9ab77c1e0/src/base.js#L49-L50) you can see the `deduplicationTag` and `deduplicationTagPattern` are brought in first from the config (a place for you to override them externally), and if not there, then the bridge application, and if not there, then it defaults to the '[m]'

you can see the default value here https://github.com/AndrewJDR/matrix-puppet-bridge/blob/f2aee74e0cf102775ae06529759c3aa9ab77c1e0/src/base.js#L269-L274

this should be enough information to show that you can set it in your config.json file.

the tricky part is what to set it to so that people don't see it. this works for us on imessage and so we have it coded in the bridge application there, but you can just as well use this in your config.json

https://github.com/kfatehi/matrix-puppet-imessage/blob/2fb589c6d90f7008883888c581eb25320b3734ca/index.js#L18-L23

**Comment by tfreedman** [comment]
I can confirm that this works - for anyone else wondering, just append the following to config.json right before the last closing brace.

  "deduplicationTag" : " \ufeff",
  "deduplicationTagPattern" : " \\ufeff$"
